### ISSUE TITLE
No "log file" in directory “~/.local/share/"

### ISSUE THREAD

**Issue by hamzakhalid34** [megabyte-labs/install.doctor#100]
### ❔ What are you experiencing an issue with?

Latest Release

### ❔ Version

Latest

### 🐞 Description

I setup ubuntu 23.04 on a virtual machine with 508GB of hard drive, 6046MB of RAM & 3 Processors, then i run the provisioning using bash <(curl -sSL https://install.doctor/start) command. but when provisioning completes, it states that are logs are stored in “~/.local/share/install.doctor.$(date+%s).log. as shown below. But it creates no log file in that directory.

![Screenshot from 2023-08-15 19-35-16](https://github.com/megabyte-labs/install.doctor/assets/97253404/face7558-d768-49f4-889f-674d6dd5e383)

the screenshot of directory is attached, there is no log file in it.
![WhatsApp Image 2023-08-15 at 7 49 01 PM](https://github.com/megabyte-labs/install.doctor/assets/97253404/2333311b-dfaf-40c6-9c03-8970b2e16d59)

### ⏺️ Steps To Reproduce

1. Setup a VM with Ubuntu 23.04 having disk space of 508GB , 6046MB of RAM & 3 Processors.
2. Install Curl & git using sudo apt install curl, sudo apt install git
3. run bash <(curl -sSL https://install.doctor/start)

**Comment by ProfessorManhattan** [comment]
Fixed this. Manually added.
