### ISSUE TITLE
Error on opening “Bash” & “Default” terminal.

### ISSUE THREAD

**Issue by hamzakhalid34** [megabyte-labs/install.doctor#101]
### ❔ What are you experiencing an issue with?

Latest Release

### ❔ Version

Latest

### 🐞 Description

I setup ubuntu 23.04 on a virtual machine with 508GB of hard drive, 6046MB of RAM & 3 Processors, then i run the provisioning using bash <(curl -sSL https://install.doctor/start) command. but when the provisioning completes, i am getting the following error when opening "Bash" and "Default" terminals

![WhatsApp Image 2023-08-15 at 7 51 29 PM](https://github.com/megabyte-labs/install.doctor/assets/97253404/8a3b61b9-32ce-4783-9db3-6476822c4de5)

### ⏺️ Steps To Reproduce

1. Setup a VM with Ubuntu 23.04 having disk space of 508GB , 6046MB of RAM & 3 Processors.
2. Install Curl & git using sudo apt install curl, sudo apt install git
3. run bash <(curl -sSL https://install.doctor/start)

**Comment by ProfessorManhattan** [comment]
Fixed. Manually added fix.
