### ISSUE TITLE
Create Useful set of Netdata Alert Definitions

### ISSUE THREAD

**Issue by ProfessorManhattan** [megabyte-labs/install.doctor#18]
### 💡 Feature/Idea

This issue basically involves taking a deep dive into the Netdata documentation and implementing all the nice-to-haves low-hanging fruit that the documentation details.

We are already including Netdata into most of our templates. Netdata is a pretty sweet way of browsing through system metrics but in order for it to be truly useful, we need to implement a set of alert configurations. The alerts should include the alerts detailed on this page: https://learn.netdata.cloud/docs/alerts-and-notifications/configure-alerts

You can also use this GH repo as a reference: https://github.com/lKhanl/netstat-my-alerts

While you're tackling this issue, also be mindful of how we can extend Netdata to better suite our purposes. For example, it would be cool if we could track the number of system / homebrew packages with reported security alerts and then alert the user whenever there is a new security message for one of the installed packages. Granted, there might be a better way of handling this but we should explore leveraging Netdata to provide this feature since we are already integrating it. You should go through https://learn.netdata.cloud/docs/data-collection/monitor-anything/ and integrate all their examples that coincide with the tools that Install Doctor is providing.

The following alert notification integrations should be included:

1. https://learn.netdata.cloud/docs/alerts-and-notifications/notifications/agent-alert-notifications/syslog
2. https://learn.netdata.cloud/docs/alerts-and-notifications/notifications/agent-alert-notifications/email
3. https://learn.netdata.cloud/docs/alerts-and-notifications/notifications/agent-alert-notifications/slack

**Comment by Haelamarketing** [comment]
Hello
