### ISSUE TITLE
Implement envchain

### ISSUE THREAD

**Issue by ProfessorManhattan** [megabyte-labs/install.doctor#23]
### 💡 Feature/Idea

Right now environment variables (API keys etc.) are being stored in `home/dot_config/shell/private_private.sh.tmpl`. This is not exactly secure. We can improve security by implementing `envchain` (https://github.com/sorah/envchain).

Write a script in `home/.chezmoiscripts/universal/*.sh.tmpl` that scans the `private_private.sh.tmpl` file and imports all the variables into `envchain` and then deletes the `profile_profile.sh.tmpl` file. In environments where this is not possible with the system keyring, skip the `envchain` and leave the `profile_profile.sh.tmpl` file in  place.

Be sure to make the logic idempotent.

**Comment by enggnr** [comment]
@ProfessorManhattan, the documentation recommends against changing the source/destination state when `chezmoi` is running - https://www.chezmoi.io/reference/application-order. 
> chezmoi assumes that the source or destination states are not modified while chezmoi is being executed. This assumption permits significant performance improvements, including allowing chezmoi to only read files from the source and destination states if they are needed to compute the target state.
chezmoi's behavior when the above assumptions are violated is undefined. For example, using a run_before_ script to update files in the source or destination states violates the assumption that the source and destination states do not change while chezmoi is running.

Can we instead remove the file `~/.config/shell/private.sh` at the end? The `tmpl` file does not hold the actual data as such, so leaving it in the filesystem does not pose a greater risk than leaving the file `private.sh`.

**Comment by ProfessorManhattan** [comment]
I don't think this is an issue with chezmoi the private shell file is idempotent
