### ISSUE TITLE
Provisioning script unable to install “go” package via apt

### ISSUE THREAD

**Issue by hamzakhalid34** [megabyte-labs/install.doctor#91]
### ❔ What are you experiencing an issue with?

Latest Release

### ❔ Version

Latest

### 🐞 Description

I setup ubuntu 23.04 on a virtual machine with 508GB of hard drive, 6046MB of RAM & 3 Processors, then i run the provisioning using bash <(curl -sSL https://install.doctor/start) command. but i am getting the following error

![image](https://github.com/megabyte-labs/install.doctor/assets/97253404/312071ed-cec1-4d24-9070-269a9009d527)

### ⏺️ Steps To Reproduce

1. Setup a VM with Ubuntu 23.04 having disk space of 508GB , 6046MB of RAM & 3 Processors.
2. Install Curl & git using sudo apt install curl, sudo apt install git
3.  run bash <(curl -sSL https://install.doctor/start)

**Comment by ProfessorManhattan** [comment]
Fixed
