### ISSUE TITLE
Provisioning script unable to build “runsc”

### ISSUE THREAD

**Issue by hamzakhalid34** [megabyte-labs/install.doctor#92]
### ❔ What are you experiencing an issue with?

Latest Release

### ❔ Version

Latest

### 🐞 Description

I setup ubuntu 23.04 on a virtual machine with 508GB of hard drive, 6046MB of RAM & 3 Processors, then i run the provisioning using bash <(curl -sSL https://install.doctor/start) command. but i am getting the following error
![image](https://github.com/megabyte-labs/install.doctor/assets/97253404/27290095-9f71-4d86-99e6-02f28126cbe9)

### ⏺️ Steps To Reproduce

1. Setup a VM with Ubuntu 23.04 having disk space of 508GB , 6046MB of RAM & 3 Processors.
2. Install Curl & git using sudo apt install curl, sudo apt install git
3. run bash <(curl -sSL https://install.doctor/start)

**Comment by ProfessorManhattan** [comment]
Increased the timeout - marking as closed
