### ISSUE TITLE
Provisioning script unable to install “docker plugin”

### ISSUE THREAD

**Issue by hamzakhalid34** [megabyte-labs/install.doctor#94]
### ❔ What are you experiencing an issue with?

Latest Release

### ❔ Version

Latest

### 🐞 Description

I setup ubuntu 23.04 on a virtual machine with 508GB of hard drive, 6046MB of RAM & 3 Processors, then i run the provisioning using bash <(curl -sSL https://install.doctor/start) command. but i am getting the following error

![WhatsApp Image 2023-08-15 at 5 29 05 PM(1)](https://github.com/megabyte-labs/install.doctor/assets/97253404/e4cc0477-779a-456e-a12a-5c8372df5ba7)

### ⏺️ Steps To Reproduce

1.  Setup a VM with Ubuntu 23.04 having disk space of 508GB , 6046MB of RAM & 3 Processors.
2.  Install Curl & git using sudo apt install curl, sudo apt install git
3.  run bash <(curl -sSL https://install.doctor/start)

**Comment by ProfessorManhattan** [comment]
Fixed
